### ISSUE TITLE
/usr/src/app/.env not found; program crashes

### ISSUE THREAD

**Issue by ddbruce** [rpiambulance/slack-link#7]
**Describe the bug**
`dotenv` doesn't hard fail if `.env` isn't available, but this looks for an error and crashes if one exists. This should not hard fail, because env vars are not always supplied by `dotenv`; often, in production, they're set in `docker-compose.yml` or elsewhere.

**Screenshots**
...
```slack-link        | Error: ENOENT: no such file or directory, open '/usr/src/app/.env'
slack-link        |     at Object.openSync (fs.js:451:3)
slack-link        |     at Object.readFileSync (fs.js:353:35)
slack-link        |     at Object.config (/usr/src/app/node_modules/dotenv/lib/main.js:96:29)
slack-link        |     at Object.<anonymous> (/usr/src/app/server.js:1:31)
slack-link        |     at Module._compile (internal/modules/cjs/loader.js:945:30)
slack-link        |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
slack-link        |     at Module.load (internal/modules/cjs/loader.js:798:32)
slack-link        |     at Function.Module._load (internal/modules/cjs/loader.js:711:12)
slack-link        |     at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
slack-link        |     at internal/main/run_main_module.js:17:11 {
slack-link        |   errno: -2,
slack-link        |   syscall: 'open',
slack-link        |   code: 'ENOENT',
slack-link        |   path: '/usr/src/app/.env'
slack-link        | }
slack-link        | npm ERR! code ELIFECYCLE
slack-link        | npm ERR! errno 1
slack-link        | npm ERR! slack-link@1.0.0 start: `node server.js`
slack-link        | npm ERR! Exit status 1
```

**Comment by ddbruce** [comment]
Issue located at https://github.com/rpiambulance/slack-link/blob/8192ad7dd070ea9f03bb644c2da46d5d02cad93a/server.js#L10

**Comment by ddbruce** [comment]
Changing `const env = require('dotenv').config();` to `require('dotenv').config();` and removing the `env.error` check should fix this.
